### PR TITLE
Update bootstrap-switch to v3.4.0.

### PR DESCRIPTION
**Pull request by XhmikosR**
The previous version didn't support Bootstrap 4.x.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Now I see https://github.com/ColorlibHQ/AdminLTE/commit/533a76538c98c06be7328176dffa562720edf4ac#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 but it doesn't mention why it was reverted?

**Comment by REJack** [comment]
One of our users found a massive bug in v3.4.0 also it's only published on npm but there is no github tag for v3.4.0, reference issue is #2605.

**Comment by XhmikosR** [comment]
I agree about it not being published on GitHub, but that could probably be something they missed. That being said, 3.3.4 isn't compatible with Bootstrap 4.x.

Has the issue been reported upstream?

**Comment by XhmikosR** [comment]
It seems that project is poorly maintained. I'll close this PR, but better look for an alternative if the issues aren't fixed soon :/

https://github.com/Bttstrp/bootstrap-switch/issues/717

**Comment by REJack** [comment]
Yeah I know it's not maintained right now from the author, also since I've decided to drop jquery with v4 (like BS5 will do), I'll need to search good alternatives for the most 3rd-plugins.

**Pull request closed without merging**
