### PR TITLE
Sidebar Search

### LINKED ISSUE #2472: Search in sidebar
Is your feature request related to a problem? Please describe.
When the sidebar is becoming huger, it's hard to find the right one. Could you possible to provide the search functions.

Describe the solution you'd like
Add the demo how to do search in sidebar.

The format like below screenshots or highlight the results or hidden or other formats.
image

image

Thanks.

### PR DESCRIPTION
**Pull request by REJack**
## Sidebar Search

This PR brings a complete new JS Plugin called Sidebar Search,
with this Plugin you can search through your sidebar items and find the correct ones, including path to the items itself.

grafik grafik grafik

#### ToDo
- [x] Search Highlighting
- [x] Docs Section

@GerryGe Feel free to test it 😄 

Closes #2472

### CODE REVIEW

**Comment by XhmikosR** [comment]
@REJack this introduces 2 new LGTM alerts that should be fixed.

**Comment by XhmikosR** [comment]
One is a potential XSS here:

https://github.com/ColorlibHQ/AdminLTE/blob/d3a552db713a2b57f6311474b4d4fa39b9b4fd99/build/js/SidebarSearch.js#L100

You should not ignore the LGTM alerts and someone should set up CodeQL for the repo ASAP...

**Comment by GerryGe** [comment]
@REJack I have opened a new ticket for the enhancement request, please see #2888

**Comment by sachiotomita** [comment]
This causes

**Comment by sachiotomita** [comment]
Hi, 
I found this causes the error below, on init
`Uncaught TypeError: Cannot read property 'toLowerCase' of undefined`
since the option value is true as default

https://github.com/ColorlibHQ/AdminLTE/blob/45d4759ab0aa104e63743395bfdedcdd909b0e22/build/js/SidebarSearch.js#L41

https://github.com/ColorlibHQ/AdminLTE/blob/45d4759ab0aa104e63743395bfdedcdd909b0e22/build/js/SidebarSearch.js#L161

**Comment by XhmikosR** [comment]
Don't get me wrong, but why was this merged without proper review? There are multiple issues with this PR, including security issues, TypeErrors and bad indentation of template literals.

**Comment by REJack** [comment]
> Don't get me wrong, but why was this merged without proper review? There are multiple issues with this PR, including security issues, TypeErrors and bad indentation of template literals.

@XhmikosR I know what you mean :/ but I don't have somebody that reviews my PR's . I'll fix the issues today and create a PR for it then you can review it :smiley: 

The TypeErrors are strange I tested it in many way and it doesn't throwed a TypeError in my tests, may there is a missing class in the markup.

**Comment by XhmikosR** [comment]
I think the TypeErrors are because one can simply not have the component, hence the class is not present. Feel free to CC me and I'll try to review it.

The problem with AdminLTE is that there are no unit tests. Unfortunately, I don't have the time to work on that, but it's the only solution to having a stable codebase.

**Comment by REJack** [comment]
@sachiotomita Please post your sidebar search form markup, I can't reproduce this.

> The problem with AdminLTE is that there are no unit tests. Unfortunately, I don't have the time to work on that, but it's the only solution to having a stable codebase.

Yep I know, I doesn't had time to work on the unit tests 😞. Also I've never added unit tests in JS, I only added unit test in PHP 🤣.

**Comment by XhmikosR** [comment]
Just try any page without a sidebar and you should see the TypeError.

**Comment by REJack** [comment]
> Just try any page without a sidebar and you should see the TypeError.

Oh yeah 🤦

**Comment by Jiannan28** [comment]
Facing the same issue. Just would like to know if there is any update on that? Or quick solution if no need the search sidebar? Thanks

**Pull request merged**
