### PR TITLE
Layout.js lint fixed

### PR DESCRIPTION
**Pull request by danny007in**
Lint Fixed #3174

### CODE REVIEW

**Comment by danny007in** [comment]
@REJack @XhmikosR  this PR has improved performance

**Before**
Screenshot 2020-11-30 180059

**After**
Screenshot 2020-11-30 180138

**Comment by XhmikosR** [comment]
That's not possible, it's basically the same thing.

**Comment by XhmikosR** [comment]
Please target the proper branch and not master.

**Comment by danny007in** [comment]
> Please target the proper branch and not master.

Sorry I am beginner for this kind of task.
ill try now

**Pull request closed without merging**
