### PR TITLE
add pagination month

### LINKED ISSUE #2585: Month Pagination
hi. could you add monthly pagination?
this link should show the example
https://webdesignerwall.com/wdw-snippet/bootstrap-month-pagination

### PR DESCRIPTION
**Pull request by REJack**
Preview 
grafik

Closes #2585

### CODE REVIEW

**Comment by XhmikosR** [comment]
Someone should look into adding Netlify to the repo for PR previews; it should make reviews easier. We'll see what we are going to deploy: only the pages and/or the docs.

**Comment by REJack** [comment]
> Someone should look into adding Netlify to the repo for PR previews; it should make reviews easier. We'll see what we are going to deploy: only the pages and/or the docs.

That's a nice idea 😄 I look if I can set it up

**Comment by XhmikosR** [comment]
@REJack I don't have the time to review everything. When I said CC me in PRs, I meant only PRs that you are not sure about :)

**Comment by REJack** [comment]
@XhmikosR Ok 😄 could you review the fullscreen PR (#2906)? The other PRs are only enhancements or small changes :P.

**Pull request merged**
