### PR TITLE
permit child indent in sidebar-collapse when focus

### PR DESCRIPTION
**Pull request by paul45**
permit child indent in sidebar-collapse when focus

### CODE REVIEW

**Comment by danny007in** [comment]
> 
> 
> permit child indent in sidebar-collapse when focus

Edit scss files not in css.
First check readme, before contribute 😄

**Comment by paul45** [comment]
ok sorry

I am not good with scss 

what du you think about the modification 

maybe someone could rewrite in scss

**Comment by danny007in** [comment]
> 
> 
> ok sorry
> 
> I am not good with scss
> 
> what du you think about the modification
> 
> maybe someone could rewrite in scss

By adding this feature, user interface may not be good 🤔

**Comment by REJack** [comment]
I see no difference with this change, may a Video or some Screenshots would help to know whats your result of the change.

Also @danny007in is right, you should never change css files here caused that they get rebuild from the scss files every release.

SCSS is not witchcraft, it's basicly CSS with some extra features like nesting, functions & variables.

**Pull request closed without merging**
