### PR TITLE
Fix: sidebar light in dark-mode

### PR DESCRIPTION
**Pull request by danny007in**
Perfect Fix: https://github.com/ColorlibHQ/AdminLTE/issues/3449

### CODE REVIEW

**Comment by REJack** [comment]
looks good, are you ready to merge? 😄

**Comment by danny007in** [comment]
better way is adding `!important` in the below line

https://github.com/danny007in/AdminLTE/blob/7fe15cfc72c73409a5fd02845025ffca56a5b78d/build/scss/_main-sidebar.scss#L231

which is better

**Comment by REJack** [comment]
I prefer the first tweak (PR), not the `!important` tweak

**Comment by danny007in** [comment]
- After squash
- Test
- Release V3.1

**Pull request merged**
