### PR TITLE
Add RTL feature in minimal way we can.

### PR DESCRIPTION
**Pull request by AliShareei**
Hi guys.

First Thank you for your great Admin Theme.
Since adding the RTL feature requires a lot of coding in all example pages.

In this PR, I will add this feature in the simplest way. These codes have no effect on the original code but help others to more easily add the RTL feature to their projects.

Issue #2236

| adminlte-ltr| adminlte-rtl

### CODE REVIEW

**Comment by danny007in** [comment]
Check Lint error https://github.com/ColorlibHQ/AdminLTE/pull/3293/checks?check_run_id=1673044046 clear it.
Use vscode and ESLint extention

**Comment by danny007in** [comment]
You should not change in .css, u must only make changes in .scss

**Comment by danny007in** [comment]
https://github.com/ColorlibHQ/AdminLTE#how-to-contribute Check it

**Comment by AliShareei** [comment]
Hi @danny007in, 
Thanks for you reveiw.

What's Lint? I don't know what's that.
About SCSS Unfortunately, I do not know correctly I have to write my code in that part.
If we had a specific file there in which I just wrote my code, I could work on it in the next PR.
But I'm not sure some Styles had scss version for example bootstrap RTL which I include in RTL.css

**Comment by danny007in** [comment]
Check each thing in package.json file, for urs understanding.
And RTL will be added in v4

**Comment by danny007in** [comment]
U can close this PR

**Comment by danny007in** [comment]
> 
> 
> https://github.com/ColorlibHQ/AdminLTE#how-to-contribute Check it

edit in only scss not css

**Comment by danny007in** [comment]
Check out https://github.com/ColorlibHQ/AdminLTE/pull/3231

**Comment by AliShareei** [comment]
@danny007in For now I fix Lint Errors.

About #3231 I think it would be a great help to find how can I implement RTL in scss. 
I will check that PR for the next days and if I had any question will be posted on here. 
But it may take time because the styles seem to have to be rewritten.

If you pay attention to line 13 of the adminlte-rtl.css file in my PR. 
the section of `RTL fix for bootstrap` it is bootstrap rtl fixer in raw css.
how can we put that section on scss?

**Comment by danny007in** [comment]
> 
> 
> Check each thing in package.json file, for urs understanding.
> And RTL will be added in AdminLTE v4

And i am Closing this PR.

U can create another PR after urs implement in scss.

**Comment by danny007in** [comment]
https://getbootstrap.com/docs/5.0/getting-started/rtl/ Check it out

**Pull request closed without merging**
