### PR TITLE
Parallel nodemon fixed

### PR DESCRIPTION
**Pull request by danny007in**

### CODE REVIEW

**Comment by XhmikosR** [comment]
You don't need concurrently. Please @REJack review @danny007in's PRs more carefully.

**Comment by danny007in** [comment]
> 
> 
> You don't need concurrently. Please @REJack review @danny007in's PRs more carefully.

@XhmikosR  its because of https://github.com/ColorlibHQ/AdminLTE/issues/3212

**Comment by XhmikosR** [comment]
I don't have the time to look at 3212 and I'm pretty sure there's no issue with nodemon.

It's clear to me that you are trying to learn and that's fine. But you don't follow basic principles like not adding a new dep for simple things. `npm-run-all` already has a `--parallel` flags. This PR is useless AFAICT. And generally, PRs need more close reviews.

/me is out

**Comment by danny007in** [comment]
> 
> 
> I don't have the time to look at 3212 and I'm pretty sure there's no issue with nodemon.
> 
> It's clear to me that you are trying to learn and that's fine. But you don't follow basic principles like not adding a new dep for simple things. `npm-run-all` already has a `--parallel` flags. This PR is useless AFAICT. And generally, PRs need more close reviews.
> 
> /me is out

hi @XhmikosR please check at #3212 and
Because in windows 10 (But in linux macOS working fine), nodejs above v14 and v15,
`npm-run-all --parallel` not working with nodemon.
that is reason i created this PR

**Pull request merged**
