### PR TITLE
Use an object when setting multiple CSS properties

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
BTW I don't have any benchmark, the alternative would be to chain the calls.

**Comment by REJack** [comment]
I've benchmarked it with [measurethat.net](https://www.measurethat.net/Benchmarks/Show/8459/0/jquery---css-multiple-vs-css-single-stack-vs-css-single) (Object vs Chained vs Single Rows). It looks like chained is faster then the other two.

**Comment by XhmikosR** [comment]
Yeah, that's why I have suggested that most CSS is moved out of JS.

Either way, this patch should be the same performance-wise with what happens on master. Also, this is consistent with the rest of the codebase.

**Comment by XhmikosR** [comment]
BTW I do plan to cache the selectors later, still splitting the patches

**Comment by XhmikosR** [comment]
@REJack so can we move this so that I move to the rest of the perf JS improvement tweaks?

**Comment by REJack** [comment]
> @REJack so can we move this 

Like merge it?

**Comment by XhmikosR** [comment]
Yeah, typo, I meant move with this. :)

**Comment by REJack** [comment]
Sure, I will prep the version after merging it to v3.1.0-pre 😄

**Pull request merged**
