### PR TITLE
Remove glyphicon leftovers.

### LINKED ISSUE #2746: [FEATURE] Remove glyphicons code?
Are glyphicons supported? If not any references should be dropped from the code :)

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #2746

### CODE REVIEW

**Comment by XhmikosR** [comment]
We don't build the dist files frequently upstream because of the noise. IMHO building only when making a release is cleaner :)

**Comment by REJack** [comment]
That's a good way too :P I only use the builded dist files to compare if anything got changed beside my changes.

**Comment by REJack** [comment]
@XhmikosR One offtopic question 😄, is there a ETA for the bootstrap 5 release?

**Comment by XhmikosR** [comment]
We plan to release alpha1 in the next 2 weeks. We are already late, I know...

**Comment by REJack** [comment]
Ok sweet 😄

**Pull request merged**
