### PR TITLE
Added remember state option to pushmenu/sidebar menu

### PR DESCRIPTION
**Pull request by gintsmurans**
As title says, this will add option to remember menu via data attributes.

### CODE REVIEW

**Comment by REJack** [comment]
Overall a nice PR, but I'm personally not a friend of cookies, I would preferr a option between cookie & localStorage and also I miss the enable/disable option for it.

**Comment by gintsmurans** [comment]
Those are some good points, updated code.

**Comment by lenamtl** [comment]
Is this possible to have the JS compiled file for this for a temporary solution ?

**Comment by lenamtl** [comment]
Hi,
I'm having issue with this code, 
This occurred when url have a # fr example **index4.php#**
Then refresh the page 
all items are now selected 

To reproduce
let say we are on index.php
we click on vertical menu parent item to open sub-menu the parent item has `<a href="#" class="nav-link ">`
so now the url is index.php#
refresh the page
all menu item are now active

**Comment by danny007in** [comment]
add true or false in toRemeber in _config

**Comment by danny007in** [comment]
can you add here https://github.com/ColorlibHQ/AdminLTE/blob/v4-dev/src/partials/_scripts.html

**Comment by danny007in** [comment]
fixed in https://github.com/ColorlibHQ/AdminLTE/commit/93c1e370fa40fde73e34e53285afed2a2cc4a0db

**Comment by danny007in** [comment]
Make PR commit readable https://www.youtube.com/watch?v=gXCkYkLQ3To

**Pull request closed without merging**
