### PR TITLE
Added VS Code Badge

### PR DESCRIPTION
**Pull request by anilloutombam**

### CODE REVIEW

**Comment by anilloutombam** [comment]
@danny007in Which  branch should i target,seems issue here

**Comment by danny007in** [comment]
taget master branch

and

add 2 badges

**Comment by anilloutombam** [comment]
> target master branch
> 
> and
> 
> add 2 badges

Do you want me to add same badge twice or ??

**Comment by REJack** [comment]
@danny007in there is way to specify the branch actually

**Pull request merged**
