### PR TITLE
Fixed height brand-link

### PR DESCRIPTION
**Pull request by dima-bzz**

### CODE REVIEW

**Comment by REJack** [comment]
Did you tested the fixed brand-link height with the text-sm classes?

**Comment by dima-bzz** [comment]
No

**Comment by REJack** [comment]
I tested your changes, this will break by users the brand-link height when they use text-sm.
If you change this to a extra class I will merge this PR otherwise not.

**Comment by dima-bzz** [comment]
If unchanged, the brand-link line does not match the navbar

brand-link

**Comment by REJack** [comment]
Then you need to increase the negative margin around your image. or change this as a extra class instead of an overall override.

**Pull request closed without merging**
