### PR TITLE
Few issues & dist files

### PR DESCRIPTION
**Pull request by gintsmurans**
Hi! 

Here are some changes I have done for a project I am working on. Feel free to merge them, if you find them a good addition to AdminLTE.

In short:
- Column sizing didn't work well, if content was too big for the screen size. Found out about "fr" unit that seems to fix the issue.
- Added Remember state option to sidebar menu.
- Fixed border color between thead, tbody and tfoot.
- Added dist files so theme is easy to be included using another transpilation proceses, especially js files as source is written in typescript and not every project is setting up typescript in their development. Although, from what I can tell, somebody has already done this.

### CODE REVIEW

**Comment by puikinsh** [comment]
Sveiks, Gint! 
Milzīgs prieks redzēt latviešus piedaloties atvērtā koda izstrādē. Paldies par dalību un ieguldīto darbu! 
Drīzumā izskatīsim un ziņosim par tālāko rīcību. Paldies!

**Comment by danny007in** [comment]
@gintsmurans 

do not add dist file in PR.

> Added Remember state option to sidebar menu.
Create Seperate PR for this

**Comment by gintsmurans** [comment]
Will create new PRs

**Comment by gintsmurans** [comment]
> Sveiks, Gint! Milzīgs prieks redzēt latviešus piedaloties atvērtā koda izstrādē. Paldies par dalību un ieguldīto darbu! Drīzumā izskatīsim un ziņosim par tālāko rīcību. Paldies!

Čau! Latviešus šeit bieži negādās manīt. Patīkams pārsteigums. :)

**Pull request closed without merging**
