### PR TITLE
resolve #1854

### LINKED ISSUE #1854: Sidebar menu tree dropdown always open
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  v2.4.0
* Operating System:  Windows 10
* Browser (Version):  Chrome ( 65.0.3325.181 - Latest), Firefox (59.0.2 - Latest)

### Description:
You can reproduce the bug here https://adminlte.io/themes/AdminLTE/pages/examples/profile.html with one of the browser versions that I use, the sidebar dropdown will only stay opened as you can see in this video https://i.gyazo.com/9858b6a02c35372275a1da6478d3aeba.mp4

### PR DESCRIPTION
**Pull request by CoderSquirrel**
Sidebar was glittchin and no collpasin, i've managed it , not perfect but like 89%, with only css

### CODE REVIEW

**Comment by henri9813** [comment]
Hello @CoderSquirrel 

Can you please update your pull request please ? 

Thanks

**Comment by CoderSquirrel** [comment]
@henri9813  i'm short of time for next couple of days, but till the end of next week i'll update then ;)

**Comment by CoderSquirrel** [comment]
hi @henri9813 i just saw that @REJack commited and merged with the same solution. Still need it commit?

**Comment by henri9813** [comment]
Hello @CoderSquirrel ,

Thanks for your reply, 
So... it's not necessary :/ 

Sorry for the inconvenience.

Regards

**Pull request closed without merging**
