### PR TITLE
Specify `diplay=fallback` for Google Fonts

### PR DESCRIPTION
**Pull request by XhmikosR**
Requires #2736 merged.

We could go with any of other options too, like `swap`, let me know if you want me to change this.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@REJack https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

Let me know which one you want :)

**Comment by XhmikosR** [comment]
PS. You should specify `Delete HEAD branches` in the repo options. Also, personally I always protect branches and require them to be up to date. the GitHub offers a button to update the branch if it's behind. :)

**Comment by REJack** [comment]
I would use `fallback` 😄   I've enabled `Delete HEAD branches`.

> Also, personally I always protect branches and require them to be up to date. the GitHub offers a button to update the branch if it's behind. :)

Did you managed this with a protection rule? Tell me more about it 🤣

**Comment by XhmikosR** [comment]
https://help.github.com/en/github/administering-a-repository/about-protected-branches

Basically protect master and v2 branches and enable the option for the branches to be up to date. You as an admin can still push directly, but you can't delete or force push a protected branch (unless you enable the relevant options, but you shouldn't :))

**Comment by XhmikosR** [comment]
Feel free to merge this if it LGTY :)

**Pull request merged**
