### PR TITLE
Consistency edits, whitespace changes, cosmetic changes, etc.

### PR DESCRIPTION
**Pull request by wpyh**
I'm studying your code, I think as a template most files would have a similar structure. These changes make for better consistency, and I will create a series of pull requests so that you can pick the changes you want to merge. Thank you.

### CODE REVIEW

**Comment by wpyh** [comment]
I have not fundamentally changed any logic, most of them are just cosmetic changes. The last commit re-organizes some "link href" and "script src" tags, but they should not have any ordered dependencies, so I think I have not broken anything.

**Comment by almasaeed2010** [comment]
I'd feel better if someone else can test approve these changes. Unfortunately, I don't have enough time to check this. 

Thanks @wpyh for the work!

**Comment by wpyh** [comment]
@hendimarcos sorry, could you point out which line it was?

**Comment by hendimarcos** [comment]
commit 493cfb90f1801bd40b8c43ff219b80c4917afb71 - Fix indentation of `<span class="input-group-btn">`
click the commit link above
only cosmetic :P

**Comment by wpyh** [comment]
@hendimarcos  Oh I see what you mean.

Actually, please consider the following </span> ... I was aligning to the </span> below it, rather than to the <input above it.

**Comment by REJack** [comment]
@hendimarcos Does this PR break something or it is stable to merge?

I'll merge this PR, if it is reviewed with a good response.

**Pull request closed without merging**
