### PR TITLE
Add CodeQL

### PR DESCRIPTION
**Pull request by XhmikosR**
I excluded the plugins folders because otherwise it takes too long to scan. That being said, I suggest that you scan everything in a temp branch (for example https://github.com/ColorlibHQ/AdminLTE/security/code-scanning?page=1&query=ref%3Arefs%2Fheads%2Fcodeql-test), report any issues upstream and/or consider using other plugins if there are replacements.

Obviously you should wait a bit for the upstream developers to have a look at these issues because some might be false positives :)

PS. I already contacted the OverlayScrollbars dev so that's one less project to contact

### CODE REVIEW

**Comment by REJack** [comment]
> report any issues upstream and/or consider using other plugins if there are replacements.

With v4.0.0 we will replace/remove many Plugins since I will drop the jQuery support so all jquery based plugins will removed if no replacement is found or it has an own dependency less version.

**Comment by XhmikosR** [comment]
I still think you should report the issues upstream, because they might not be aware of any potential issues.

Also, do not forget that the current patch doesn't scan the plugins because it's a lot slower. So, you will need to make a temp branch like I did above to check the plugins.

**Review by danny007in — APPROVED** [review]

**Comment by REJack** [comment]
@XhmikosR can I disable LGTM now with this PR merged?

**Comment by XhmikosR** [comment]
They are not 100% the same, so better keep both IMHO.

**Comment by REJack** [comment]
Alright 👌🏼

**Pull request merged**
