### PR TITLE
Flatten package-lock.json

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by danny007in** [comment]
how to do like this

**Comment by XhmikosR** [comment]
> 
> 
> how to do like this

You clean up your local node_modules and regenerate the lock file. But needs attention, it's not always safe to do so, and further actions might be needed.

**Comment by XhmikosR** [comment]
@REJack this should be merged before any other dependabot PRs.

**Comment by REJack** [comment]
@XhmikosR I wanted to ask you this 🤣 then I have seen your comment.
Bildschirmfoto 2021-01-18 um 08 14 00

I look over the PRs now and merge them ^^ I looked partially over them already.

**Comment by XhmikosR** [comment]
Yet someone is merging the dependabot PRs...

**Comment by XhmikosR** [comment]
@danny007in please stop merging the dependabot PRs!

@REJack these PRs will be the last ones I'll open FYI.

**Comment by danny007in** [comment]
Ok i am stopping

**Review by danny007in — APPROVED** [review]

**Pull request merged**
