### PR TITLE
docs(readme): Totorial add into readme

### PR DESCRIPTION
**Pull request by shailesh-ladumor**

### CODE REVIEW

**Comment by REJack** [comment]
Place your change in the implementations section inside the docs and not in the repo readme.

**Comment by shailesh-ladumor** [comment]
Can you please give me link where should I place this?

**Comment by REJack** [comment]
Look at docs/implementations.md

**Comment by shailesh-ladumor** [comment]
Thank you very much.

**Comment by shailesh-ladumor** [comment]
@rdutra  New PR placed here https://github.com/ColorlibHQ/AdminLTE/pull/3032

**Comment by shailesh-ladumor** [comment]
> 
> 
> Look at docs/implementations.md

Done!

**Pull request closed without merging**
