### PR TITLE
Configure LGTM

### PR DESCRIPTION
**Pull request by XhmikosR**
The languages are auto-detected AFAICT.

@REJack please disable PR comments if you haven't already done it :)

Looking into the rest.

### CODE REVIEW

**Comment by REJack** [comment]
> The languages are auto-detected AFAICT.

That’s strange we have no python code in this project 🤣

> please disable PR comments if you haven't already done it :)

I've disabled the commenting on lgtm.com

**Comment by XhmikosR** [comment]
I'm not sure how to configure LGTM further :/

Also, I'm not sure if it makes sense to have it fail for 3rd-party files like the plugins files. It's nice to be able to see issues in the plugins, but it takes too long.

**Comment by XhmikosR** [comment]
I think we better merge this if you are going to keep LGTM. The limitations are it won't scan the plugins folder, but without that it takes ~18 minutes.

**Comment by REJack** [comment]
I'm good with that 😄 for now it’s ok with this limitation.

**Comment by XhmikosR** [comment]
@REJack something isn't right with the LGTM project, I see now why it autodetects that there are Python files. https://lgtm.com/projects/g/ColorlibHQ/AdminLTE/latest/files/?sort=name&dir=ASC&mode=heatmap&showExcluded=false

You can see it includes bower_components but the folder isn't present in master. Not sure how to fix this. Maybe you should contact their support and they should be able to help :)

**Comment by REJack** [comment]
I did not found any settings on LGTM beside this two options
- Automated code review for pull requests
- Commenting

But I'll look later if I found some other options 🤣

**Comment by XhmikosR** [comment]
There aren't any options that's why I said better contact their support to help with this case :)

**Comment by REJack** [comment]
Ok, I'll contact them. I have an other strange bug too. My name on LGTM is Unknown 🤣 but with the correct Avatar.
Bildschirmfoto 2020-06-01 um 14 15 34

**Comment by REJack** [comment]
I've opend a topic on LGTM.com's Forum to disable the python analysis.

**Comment by REJack** [comment]
The python analysis is disabled 😄

**Comment by XhmikosR** [comment]
You should also ask them why it shows `bower_components` even though the folder isn't present :)

**Comment by REJack** [comment]
They might check the v2 branch too 😄 I'll create a topic for this too.

**Comment by XhmikosR** [comment]
IIRC they only check the default repo branch.

**Comment by REJack** [comment]
Then it comes from an old commit ^^

**Comment by XhmikosR** [comment]
Yeah, but since the files aren't present they shouldn't be listed on lgtm. Anyway, let me know how it goes :)

**Comment by REJack** [comment]
I got a [anwser](https://discuss.lgtm.com/t/analysis-shows-folders-from-old-git-branches/2927/2?u=rejack), we can hide results for files that we are not interested using a file classifier 😄 And you was right it only check the default repo branch.

**Pull request merged**
